### ISSUE TITLE
Message Validation error when initialising sample project

### ISSUE THREAD

**Issue by philipdickinson** [Viber/sample-bot-isitup#1]
```
TypeError: Not a buffer
   at TypeError (native)
   at new Hmac (crypto.js:87:16)
   at Object.Hmac (crypto.js:85:12)
   at MessageValidator._calculateHmacFromMessage (/home/nowuser/src/node_modules/baf6ab1b53f7d259fc108c0cb6439ccabf2a8d2e/lib/message/message-validator.js:17:16)
   at MessageValidator.validateMessage (/home/nowuser/src/node_modules/baf6ab1b53f7d259fc108c0cb6439ccabf2a8d2e/lib/message/message-validator.js:11:30)
   at /home/nowuser/src/node_modules/baf6ab1b53f7d259fc108c0cb6439ccabf2a8d2e/lib/middleware.js:61:32
   at Layer.handle [as handle_request] (/home/nowuser/src/node_modules/86421e6b6de89c8645b06441570eaa27d4883cb5/lib/router/layer.js:95:5)
   at trim_prefix (/home/nowuser/src/node_modules/86421e6b6de89c8645b06441570eaa27d4883cb5/lib/router/index.js:312:13)
   at /home/nowuser/src/node_modules/86421e6b6de89c8645b06441570eaa27d4883cb5/lib/router/index.js:280:7
   at Function.process_params (/home/nowuser/src/node_modules/86421e6b6de89c8645b06441570eaa27d4883cb5/lib/router/index.js:330:12)
```

Freshly cloned repo, with the only change being creating & putting my own API key into the `.env` file. Running through now.sh as the readme instructs. Above is in browser when visiting now.sh URL; console output shows no errors:

```
> Deploying ~/repos/sample-bot-isitup
> Using Node.js 5.11.1 (requested: `>=5`)
> Ready! https://isitup-bot-wtaitilljq.now.sh (copied to clipboard) [3s]
> Initializing…
> Deployment complete!
```

**Comment by philipdickinson** [comment]
Additional info, not entirely related:

I tried running the sample project on one of my own servers instead to see what I could find, when I realised that the sample project does not appear to be using HTTPS. I updated it to start an HTTPS server on 8080 (with certs for my domain) but only get "Connection refused" back from the `set_webhook` endpoint.

I'm sure there must be something simple I am missing 😄  - will take a look again tomorrow with more verbose logging. In the mean time I think my original issue might still be of interest since I would assume others are having the same difficulties I had.

**Comment by ItamarM** [comment]
Hi @philipdickinson  thanks for letting us know. It seems that `now.sh` changed the way they handle environment variables. To ease the setup we decided to drop those all together. See our bc148cd2c95385184495bdaf89b66e8ce31c7816 commit.

Regarding your second comment. It seems you have issues with your certificates. 
Maybe the following code will assist you:
```
const https = require('https');
const port = process.env.PORT || 8080;
const webhookUrl = "https://example-bot.example.com:8080/";

const fs = require("fs");
const httpsOptions = {
	key: fs.readFileSync(__dirname + "/../server.key"),
	cert: fs.readFileSync(__dirname + "/../server.crt"),
	ca: fs.readFileSync(__dirname + "/../ca.pem")
}; // Trusted SSL certification (not self-signed).

https.createServer(httpsOptions, bot.middleware()).listen(port, () => bot.setWebhook(webhookUrl));
```

In addition, you can always fallback to [heroku](https://github.com/Viber/sample-bot-isitup/blob/master/docs/TUTORIAL.md#option-2-heroku) or any other alternative.

**Comment by philipdickinson** [comment]
Ah nice, thanks @ItamarM! I'll pull those changes and try again. Thanks for the quick response 😄

**Comment by philipdickinson** [comment]
Hmm, I still get the same error as before @ItamarM. This was with a freshly-cloned version of this repo, the only change being adding my own API key to line 59 of `index.js`. I'll take your advice and try an alternative means of deployment for the time being.

**Comment by ItamarM** [comment]
@philipdickinson have you removed the `node_modules` folder? I also updated our npm module to the latest version.

**Comment by philipdickinson** [comment]
The output from now.sh suggests that it is using the correct (1.0.6) version:

```
> Deploying ~/repos/sample-bot-isitup
> Using Node.js 5.11.1 (requested: `>=5`)
> Ready! https://isitup-bot-gsnzbflotd.now.sh (copied to clipboard) [2s]
> Upload [====================] 100% 0.0s
> Sync complete (45.36kB) [2s]
> Initializing…
> Building
> ▲ npm install
> Installing package express@4.13.4
> Installing package request@^2.79.0
> Installing package winston@^2.3.0
> Installing package eslint@^2.10.1
> Installing package winston-console-formatter@^0.3.1
> Installing package nodeunit@~0.10.2
> Installing package viber-bot@^1.0.6
> ▲ npm start
> [2017-02-15 08:18:34.260] [INFO] Sending 'setWebhook' request for url: https://isitup-bot-gsnzbflotd.now.sh
> [2017-02-15 08:18:34.266] [DEBUG] Opening request to url: 'https://chatapi.viber.com/pa/set_webhook' with data
>   url: https://isitup-bot-gsnzbflotd.now.sh
>   event_types:
>     - subscribed
>     - unsubscribed
>     - conversation_started
>     - message
>     - delivered
>     - seen
> Deployment complete!
```

**Comment by philipdickinson** [comment]
Hi @ItamarM, I decided to take a look at this again. Got a fresh clone of the repo, added my API key and updated it to create a HTTPS server instead of HTTP (all the same things as before). I'll show you the output. It seems from reading this https://support.viber.com/customer/en/portal/articles/2541103-setting-a-webhook?b_id=13518 that the server sends the setWebhook request, then Viber is sending a callback to the webhook URL, but then the server is not responding to that correctly. I notice if I curl my webhook URL when the application is running I see the same message validation error as before. Do you have any ideas? I appreciate your help with this. I'll include the error and also the output from the application when it starts too.

```
[2017-02-20 10:31:30.034] [INFO] Sending 'setWebhook' request for url: [MY URL]
[2017-02-20 10:31:30.037] [DEBUG] Opening request to url: 'https://chatapi.viber.com/pa/set_webhook' with data
  url: [MY URL]
  event_types:
    - subscribed
    - unsubscribed
    - conversation_started
    - message
    - delivered
    - seen
[2017-02-20 10:31:30.157] [ERROR] Response error
  status: 1
  status_message: Result[HttpRequest[POST  HTTP/1.1]@2a3ca559 > HttpResponse[null 0 null]@79fcd025] java.net.ConnectException: Connection refused
[2017-02-20 10:31:30.159] [DEBUG] Request ended successfully
```

```
TypeError: Not a string or buffer
   at TypeError (native)
   at Hmac.Hash.update (crypto.js:70:16)
   at MessageValidator._calculateHmacFromMessage (/tmp/viber-bot-sample/node_modules/viber-bot/lib/message/message-validator.js:17:54)
   at MessageValidator.validateMessage (/tmp/viber-bot-sample/node_modules/viber-bot/lib/message/message-validator.js:11:30)
   at /tmp/viber-bot-sample/node_modules/viber-bot/lib/middleware.js:61:32
   at Layer.handle [as handle_request] (/tmp/viber-bot-sample/node_modules/viber-bot/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/tmp/viber-bot-sample/node_modules/viber-bot/node_modules/express/lib/router/index.js:312:13)
   at /tmp/viber-bot-sample/node_modules/viber-bot/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/tmp/viber-bot-sample/node_modules/viber-bot/node_modules/express/lib/router/index.js:330:12)
   at next (/tmp/viber-bot-sample/node_modules/viber-bot/node_modules/express/lib/router/index.js:271:10)
```

**Comment by philipdickinson** [comment]
Ok @ItamarM I figured it out. It seems when I edited the sample project to use an HTTPS server I didn't update the port from 8080 to 443. Now that I have it listening on 443 everything seems to be fine! Might be worth updating the readme to make sure other people pay attention to this too.

**Comment by ItamarM** [comment]
@philipdickinson sure. happy to hear!
