### ISSUE TITLE
Can I use viber-bot as participant of some viber group?

### ISSUE THREAD

**Issue by viktordavidovich** [Viber/sample-bot-isitup#2]
Hi guys, my task sounds like below:
1) We have simple viber group with ~70 members + 3 administrators
2) One day, some viber-bot will write some message in chat, for example, "Start counting!"
After that, everybody who want to be added to the some list, let's say list of active member, this guys should answer to the GROUP CHAT (not to private message of viber-bot)" "+" or "agree"
3) After that, I would like to count numbers of messages by some mask, let's say calculate all "+"

So, general question is it possible to SUBSCRIBE and LISTEN viber group messages?? I know how to do it, if user write DIRECTLY TO PM BOT, but how to listen groups???

**Comment by hamudiiq** [comment]
ok

**Comment by viktordavidovich** [comment]
@hamudiiq Hi, any comments about my question? I just closed it due to not having answer from developers.

**Comment by elephantux** [comment]
@viktordavidovich did you find an answer?

**Comment by viktordavidovich** [comment]
@elephantux no, I didn't. I just switched to another bots framework, I mean another messager. So now I'm using Telegram and theirs Bot API. It has really good documentation and much more opportunities to develop something really cool.

**Comment by 0xCardiE** [comment]
Has this changed in any way recently?

**Comment by pctin** [comment]
Do this have some updates? I writing a bot but cannot add to Viber group to send some auto messages to all members in group.
![image](https://user-images.githubusercontent.com/7435670/70313070-7c936300-1847-11ea-813c-cb419180d798.png)

**Comment by mikekok** [comment]
Still no updates, it's a shame that Viber prevents you from adding bots to your group, that's the only reason I switched to Telegram.

**Comment by pctin** [comment]
> Still no updates, it's a shame that Viber prevents you from adding bots to your group, that's the only reason I switched to Telegram.

Yes, I also have used Telegram bots, It's so cool. However, my company bussiness is communicating with our clients in both Telegram and Viber so I need to try with Viber Bot, i'm trying to using Viber broadcast to send the same message to many users at once. So sad and disapointed when viber have no support for group!!

**Comment by mikekok** [comment]
> 
> 
> > Still no updates, it's a shame that Viber prevents you from adding bots to your group, that's the only reason I switched to Telegram.
> 
> Yes, I also have used Telegram bots, It's so cool. However, my company bussiness is communicating with our clients in both Telegram and Viber so I need to try with Viber Bot, i'm trying to using Viber broadcast to send the same message to many users at once. So sad and disapointed when viber have no support for group!!

I truly believe this is a key feature and it's a huge shame that viber hasn't already implemented this.
I will stick with Telegram for the time being, its API is way user-friendlier and has many more features.

**Comment by measproem** [comment]
I think leader of Viber's technical not so active on his career because I check API update so long and API less feature.

**Comment by VityaSchel** [comment]
Здравствуйте
я хотел просто пересылать сообщения из группы школы в наш чат телеграм
я ненавижу вайбер

**Comment by Vitalicus** [comment]
I want to create a bot for automatic messages in groups. Whet it will be possible?

**Comment by VityaSchel** [comment]
> I want to create a bot for automatic messages in groups. Whet it will be possible?

when allah creates sudniy day we all see that 🙏🙏🙏
slava allahu
